EOF = 'EOF'
PIPE = 'PIPE'
COLON = 'COLON'
COMMA = 'COMMA'

NAZIV = 'NAZIV'
TIP_PODATKA = 'TIP_PODATKA'

CEO_BROJ = 'CEO_BROJ'
STRUNA = 'STRUNA'
JESTE_NIJE = 'JESTE_NIJE'

PREKINI_PONAVLJANJE = 'PREKINI_PONAVLJANJE'

PLUS = 'PLUS'
MINUS = 'MINUS'
MNOZENJE = 'MNOZENJE'
DELJENJE = 'DELJENJE'
OSTATAK = 'OSTATAK'

JEDNAKO = 'JEDNAKO'
NIJE_JEDNAKO = 'NIJE_JEDNAKO'
MANJE = 'MANJE'
VECE = 'VECE'
MANJE_JEDNAKO = 'MANJE_JEDNAKO'
VECE_JEDNAKO = 'VECE_JEDNAKO'

LOGICKO_I = 'LOGICKO_I'
LOGICKO_ILI = 'LOGICKO_ILI'
LOGICKO_NE = 'LOGICKO_NE'

ZAGRADA_OTVORENA = 'ZAGRADA_OTVORENA'
ZAGRADA_ZATVORENA = 'ZAGRADA_ZATVORENA'

PROGRAM_POCETAK = 'PROGRAM_POCETAK'
PROGRAM_KRAJ = 'PROGRAM_KRAJ'

POSTOJANJE_POCETAK = 'POSTOJANJE_POCETAK'
POSTOJANJE_KRAJ = 'POSTOJANJE_KRAJ'

DODELA_POCETAK = 'DODELA_POCETAK'
DODELA_KRAJ = 'DODELA_KRAJ'

POLJE_POCETAK = 'POLJE_POCETAK'
POLJE_KRAJ = 'POLJE_KRAJ'

NAREDBA_POCETAK = 'NAREDBA_POCETAK'
NAREDBA_KRAJ = 'NAREDBA_KRAJ'

CELINA_POCETAK = 'CELINA_POCETAK'
CELINA_KRAJ = 'CELINA_KRAJ'

RUTINA_POCETAK = 'RUTINA_POCETAK'
RUTINA_KRAJ = 'RUTINA_KRAJ'

RUTINA_POZIV_POCETAK = 'RUTINA_POZIV_POCETAK'
RUTINA_POZIV_KRAJ = 'RUTINA_POZIV_KRAJ'

UGRADJENA_RUTINA_POZIV_POCETAK = 'UGRADJENA_RUTINA_POZIV_POCETAK'
UGRADJENA_RUTINA_POZIV_KRAJ = 'UGRADJENA_RUTINA_POZIV_KRAJ'

VRATI_POCETAK = 'VRATI_POCETAK'
VRATI_KRAJ = 'VRATI_KRAJ'

NAREDBA_USLOV = 'NAREDBA_USLOV'
NAREDBA_PONAVLJANJE = 'NAREDBA_PONAVLJANJE'

CELINA_PITANJE = 'CELINA_PITANJE'
CELINA_DA = 'CELINA_DA'
CELINA_NE = 'CELINA_NE'
CELINA_PONOVI = 'CELINA_PONOVI'
CELINA_POLJA = 'CELINA_POLJA'
CELINA_SADRZAJ_RUTINE = 'CELINA_SADRZAJ_RUTINE'
